In [35]:
import torch

arange生成tensor数组，可指定数据类型

In [36]:
x = torch.arange(12, dtype=torch.float32)
print(x)

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])


In [37]:
x.numel()

12

In [38]:
x.shape

torch.Size([12])

（1） 指定行列，改变vector的形状，reshape(行，列)
（2）只指定行，或者只指定列，reshape(-1,列)， reshape(行,-1)

In [39]:
X = x.reshape(2, -1)
print(X)

X = x.reshape(3, 4)
print(X)

tensor([[ 0.,  1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10., 11.]])
tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])


In [40]:
torch.zeros((2, 3, 4))
torch.ones((2, 3, 4))
torch.randn(3, 4)

tensor([[ 0.7686,  2.2842, -0.2979, -0.4298],
        [ 0.6109,  0.5410, -1.4706, -0.2159],
        [-0.7359,  0.8360,  0.2431, -0.0197]])

## 2. 索引与切片

In [41]:
X[-1], X[1:3]
#2代表前面冒号的1-2行都赋予同样的值
X[:2,:] = 10
X

tensor([[10., 10., 10., 10.],
        [10., 10., 10., 10.],
        [ 8.,  9., 10., 11.]])

## 3. 计算操作operations

In [42]:
torch.exp(x)

tensor([22026.4648, 22026.4648, 22026.4648, 22026.4648, 22026.4648, 22026.4648,
        22026.4648, 22026.4648,  2980.9580,  8103.0840, 22026.4648, 59874.1406])

In [43]:
#3.1 cat 拼接 [0,1,2...] dim指定沿着第几个维度拼接
X = torch.arange(12, dtype=torch.float32).reshape((3, 4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
Z = torch.cat((X, Y), dim=0) #沿着行拼接
print(Z)
Z = torch.cat((X, Y), dim=1) #沿着列拼接
Z

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 2.,  1.,  4.,  3.],
        [ 1.,  2.,  3.,  4.],
        [ 4.,  3.,  2.,  1.]])


tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
        [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
        [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]])

In [44]:
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [45]:
X.sum()

tensor(66.)

## 4. 广播
3.1 先广播成一样的矩阵形状

3.2 执行加减乘除操作

In [46]:
'''
a -> 3×1
b -> 1×2

when a + b, 
a -> 3×2, 沿着列复制
b -> 3×2, 沿着行复制

eg. a: tensor([[0],[1],[2]]) -> tensor([[0, 0],[1, 1],[2, 2]])
b: tensor([[0, 1]])) ->  tensor([[0, 1],[0,1], [0, 1]]))

'''

a = torch.arange(3).reshape(3, 1)
b = torch.arange(2).reshape(1, 2)

a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

## 5. 省略内存
(1) 使用 [:]

In [51]:
'''
Y = Y + X
系统为 Y 重新分配了一块内存，并指向新的结果，此时 new Y 与 old Y指向不同的位置，增加了内存支出
'''
before = id(Y)
Y = Y + X
id(Y) == before

False

In [54]:
Z = torch.zeros_like(Y)
print("id(X):", id(Z))

Z[:] = X + Y
print("id(X):", id(Z))

id(X): 47404998588464
id(X): 47404998588464


## 6. 数据类型转换
(1) Tensor -> Numpy: tensor.numpy()

(2) Numpy -> Tensor: from_numpy()

In [57]:
#(1) Tensor -> Numpy
A = X.numpy()
type(A)

numpy.ndarray

In [58]:
#(2) Numpy -> Tensor
B = torch.from_numpy(A)
type(B)

torch.Tensor