## 1.Scalar, vector and matrix 三者的区别
**scalar:** 1,2,3...

**vector:** tensor([0, 1, 2])

**matrix:** tensor([[0, 1],[2, 3],[4, 5]])


In [3]:
import torch

In [15]:
'''
矩阵的转置：Tensor.T
'''
A = torch.arange(6).reshape(3, 2)
A

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [16]:
A.T

tensor([[0, 2, 4],
        [1, 3, 5]])

## 2. 更大的tensor

In [17]:
# 图像中涉及到三到四维度的tensor
torch.arange(24).reshape(2, 3, 4)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

## 3. Tensor 的基本属性
(1) 复制，分配新内存 

(2) Hadamard 乘法 

(3)

In [18]:
#(1)复制，分配新内存
A = torch.arange(6, dtype=torch.float32).reshape(2, 3)
B = A.clone()
id(A),id(B), A, A + B

(47750519026416,
 47750519026704,
 tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 tensor([[ 0.,  2.,  4.],
         [ 6.,  8., 10.]]))

In [19]:
# (2) Hadamard 乘法（对应位置相乘）
A, B, A*B

(tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 tensor([[ 0.,  1.,  4.],
         [ 9., 16., 25.]]))

## 4. Reduction and Non-Reduction Sum
（1）sum，mean以及沿着axis中的行或者列计算

（2）上述计算中的keepdims表述是否回到原来的形状

In [24]:
x = torch.arange(3, dtype=torch.float32)
x, x.sum()

(tensor([0., 1., 2.]), tensor(3.))

In [35]:
A, A.shape, A.sum(), A.sum(axis=1), A.mean(axis=0)
#axis指定按照行增加还是按照列增加
A.sum(axis=[0, 1]) == A.sum()

tensor(True)

In [43]:
#在执行计算后，想要结果的形状与原来保持一致，使用keepdims

sum_A = A.sum(axis=1)
sum_A_keep = A.sum(axis=1, keepdims=True)
print("A:", A)
print("sum_A.shape", sum_A.shape, "sum_A:", sum_A)
print("sum_A_keep.shape", sum_A_keep.shape, "sum_A_keep:", sum_A_keep)

A: tensor([[0., 1., 2.],
        [3., 4., 5.]])
sum_A.shape torch.Size([2]) sum_A: tensor([ 3., 12.])
sum_A_keep.shape torch.Size([2, 1]) sum_A_keep: tensor([[ 3.],
        [12.]])


In [49]:
# cumsum 按行累加
A, A.cumsum(axis=0)

(tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 tensor([[0., 1., 2.],
         [3., 5., 7.]]))

## 5. 点乘 Dot Products
针对vectors, 对应位置相乘再累加 == elementwise multiplication follow by a sum

In [64]:
y = torch.ones(3, dtype=torch.float32)
x, y, torch.dot(x, y), torch.dot(x, y) == torch.sum(x * y)

(tensor([0., 1., 2.]), tensor([1., 1., 1.]), tensor(3.), tensor(True))

## 6. 矩阵-向量 乘法 Matrix-vector Products 
eg. **A**: m × n, vector x: n

A 的列= x的行

**torch.mv()**

In [57]:
print("A:", A, "x", x)
print("A.shape:", A.shape)
print("x.shape:", x.shape)
torch.mv(A, x)


A: tensor([[0., 1., 2.],
        [3., 4., 5.]]) x tensor([0., 1., 2.])
A.shape: torch.Size([2, 3])
x.shape: torch.Size([3])


tensor([ 5., 14.])

## 7. 矩阵-矩阵相乘 Matrix-Matrix Products
**torch.mm()**

In [59]:
B = torch.ones(3, 4)
A, B, torch.mm(A, B)

(tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 tensor([[ 3.,  3.,  3.,  3.],
         [12., 12., 12., 12.]]))

## 8. 范数 Norms-tell us how big a vector it is.
(1) **torch,norm()**: l2正则化-欧式距离：向量中的每个数值平方累加后再开方

(2) **torch.abs().sum()**: l1正则化-曼哈顿距离：向量中每个数值绝对值累加后再开方

In [61]:
#l2 正则化
u = torch.tensor([3.0, -4.0])
torch.norm(u)

tensor(5.)

In [63]:
#l1 正则化
torch.abs(u).sum()

tensor(7.)